# ===================================================================
# MHXY AI Model Factory - 实验指令单: 作战单位检测模型 v1
# ===================================================================

# --- 1. 基础信息 (唯一标识一次运行) ---
project_name: "Combat_Units"
run_name: "units_detector_v1_synth" # 'synth' 后缀表示这是用合成数据训练的

# --- 2. 任务定义 (决定使用哪种数据处理器) ---
task_type: "detector" # 这是一个目标检测任务

# --- 3. 数据流水线 (定义数据的输入) ---
# 【关键】指向我们在第一步中整合好的“原始数据”目录
source_data_dir: "data/raw/synthetic_combat_units_v1_raw"

# --- 4. 模型与训练 (定义模型本身和训练行为) ---
# 从一个标准的预训练模型开始一次全新的训练
base_model: "/home/zhz/deepl/models/yolo11n.pt" # 您也可以选择 yolov8s.pt 或更大的模型

# 【关键】定义您的28个类别。
# 您可以直接从 data/processed/synthetic_combat_units_v1/dataset.yaml 文件中复制 'names' 部分
class_names:
  0: '凤凰'
  1: '剑侠客'
  2: '地狱战神'
  3: '大海龟'
  4: '大蝙蝠'
  5: '天将'
  6: '小龙女'
  7: '山贼'
  8: '巨蛙'
  9: '强盗'
  10: '护卫'
  11: '树怪'
  12: '海毛虫'
  13: '狼'
  14: '玄彩峨'
  15: '白熊'
  16: '老虎'
  17: '舞天姬'
  18: '虾兵'
  19: '赌徒'
  20: '逍遥生'
  21: '野猪'
  22: '野猪精'
  23: '雷鸟人'
  24: '飞燕女'
  25: '骨精灵'
  26: '黑熊'
  27: '龟丞相'

# 【YOLO11 核心超参数】
# 针对这个新的、较大的数据集，可以做一些调整
hyperparameters:
  # 核心设置
  epochs: 100       # 数据量大，可以适当减少epochs，或增加patience
  patience: 20      # 20个epoch没有提升就提前停止
  batch: 32         # 如果您的显存允许，可以使用更大的batch size
  imgsz: 640
  device: 0
  workers: 8
  exist_ok: True

  # 优化器与学习率 (保持默认或微调)
  optimizer: 'auto'
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0

  # 数据增强 (保持默认即可，合成数据本身已很多样)
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  fliplr: 0.5
  mosaic: 1.0

# --- 5. 产物导出 (定义最终产品的名称) ---
onnx_output_name: "yolo_combat_units_v1.onnx"